### ISSUE TITLE
The JWS installation option should allow you to exclude natives

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#73] opened 2022-04-08 17:41 UTC
##### SUMMARY
Not everyone wants to deploy the natives zip in their environment, so we should easily allow you to disable that requirement. I don't see an easy way to do so in the current setup. I've tried setting the `jws_native_zipfile_url` to an empty string but it still tries.

```
TASK [middleware_automation.jws.jws : Install JWS native dependencies with zipfile from RHN:] ********************************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [middleware_automation.jws.jws : Copy archives to target nodes] *********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=jws-5.6.0-application-server.zip)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [localhost] (item=jws-5.6.0-application-server-RHEL35-x86_64.zip) => {"ansible_loop_var": "item", "changed": false, "item": "jws-5.6.0-application-server-RHEL35-x86_64.zip", "msg": "Could not find or access '/root/jws-5.6.0-application-server-RHEL35-x86_64.zip' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

Note that I'm testing on Fedora and even though it's an unsupported configuration I expected the JWS java only zip to install and run correctly.

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment] 2022-04-13 07:49
@csutherl I was surprised, because I remember adding something about that. Checking the code, there is this check:
```
 set_fact:
    zipfiles: "{{ zipfiles + [{ 'src': native_zipfile, 'creates': tomcat.home + '/lib/libtcnative-1.so' }] }}"
  when:
    - native_zipfile is defined
    - native_zipfile | length > 0
 ```
So, if you define native_zipfile as an empty array, it should do the tricks:
```
native_zipfile: []
```

If this indeed works for you, we'll add the much needed documentation about it (and maybe default this value to []).

**Comment by csutherl** [comment] 2022-04-13 19:24
It doesn't matter what I set `native_zipfile` to in the playbook, it doesn't change the value and results in failure :(

**Comment by rpelisse** [comment] 2022-04-14 08:27
Darn! But thanks for checking this. I'll try to reproduce and fix asap.

**Comment by rpelisse** [comment] 2022-04-22 15:45
Fixed by [PR97](https://github.com/ansible-middleware/jws-ansible-playbook/pull/97)

**Closed** 2022-04-27 14:48 UTC
Labels: bugfixes, minor_changes
